### ISSUE TITLE
Feature: Deleting an Account

### ISSUE THREAD

**Issue by lukas2511** [dehydrated-io/dehydrated#216]
ACME allows deletion of accounts, this may be implemented in letsencrypt.sh in the future

**Comment by Exagone313** [comment]
As the spec for [Account Deactivation](https://ietf-wg-acme.github.io/acme/draft-ietf-acme-acme.html#rfc.section.7.3.7) says that the server *should not* revoke certificates, should dehydrated ask for that action to the user?

**Comment by ChliHug** [comment]
I needed to deactivate some accounts and added a command to my dehydrated script. Here's the [diff](https://github.com/lukas2511/dehydrated/files/2641548/dehydrated_add_deactivate_command.diff.txt) for anyone who also just needs a quick solution. And it really is minimal. It's ACME v2 only (v1 really does not have the option?), just sends the command to the server and does not change the status or check for it in the local json file. I'm not familiar enough with the script to add that.

**Comment by cpu** [comment]
ACME v1 allows account deactivation. There's no way to delete an account in ACME v1 or ACME v2, only deactivation.

ACME v1 account deactivation works the same way as in ACME v2: Send an authenticated POST with the JWS body`{"status":"deactivated"}` to the account's URL.
