### ISSUE TITLE
Better JSON parsing

### ISSUE THREAD

**Issue by lukas2511** [dehydrated-io/dehydrated#516]
Currently dehydrated has very rudimentary JSON parsing which often results in issues with similarly-named values (like the recent #515 where dehydrated used the `url` string from a sub-dictionary instead of the root).

All JSON parsing should be replaced by something that actually "understands" the JSON structure instead of greping for values inside of it.

I had a look at JSON.sh which looks promising and I actually started stripping it down to only the required functionality and making it compatible with all the bash/zsh options set in dehydrated.

I also looked at some other "libraries" which used awk or sed for the parsing, but those seemed to be problematic on BSD and older GNU/Lunix systems.

So for now I'm planning on integrating JSON.sh, but if anybody knows about similar projects feel free to comment.

**Comment by bzed** [comment]
https://github.com/stedolan/jq is available in most distributions these days. Not on older systems, though.

**Comment by vidensky** [comment]
Step-ca authority does not work due to bad parsing of JSON.
see # 689

**Comment by lukas2511** [comment]
I'm going to prioritize work on this. Will be the next thing after getting the code-testing system running (which for me is a hard requirement before I'm going to change anything around JSON parsing).

**Comment by vidensky** [comment]
This is good news. 

Yesterday we looked at JSON.sh, https://github.com/step-/JSON.awk and https://github.com/stedolan/jq.

JQ is in my opinion the best choice. Even at the cost of dependence on another utility. JQ has been in the Debian repository since version 8. So 5 years ago. on other OS versions, we didn't look.

**Comment by lukas2511** [comment]
@vidensky Yea, i'd really like to simply use jq, but since dehydrated is running on a lot of older systems where jq is not available that would be not-so-great for a big part of the userbase. I have a prototype of a JSON.sh integration... somewhere... (it's been a while ago...), I think that would be the best route to take.

**Comment by lukas2511** [comment]
There now is an experimental branch https://github.com/dehydrated-io/dehydrated/tree/jsonsh including JSON.sh as JSON parser.

**Comment by lukas2511** [comment]
Closing this issue as JSON.sh is now integrated into the main branch. Please open separate issues if you want to report a related problem.
