### ISSUE TITLE
Add option to ignore extra domains in existing and valid certificates

### ISSUE THREAD

**Issue by bzed** [dehydrated-io/dehydrated#563]
Please add an option to allow dehydrated to ignore the case when more than the configured domains are listed in an existing SAN cert while the cert is still valid.
This would help in various cases - like migrating domains to other hosts automatically while the old IP is still cached in DNS servers. You want to have some grace period before removing names from SAN certs in such cases.

**Comment by lukas2511** [comment]
If you ever get into this situation I'd recommend to simply not tell dehydrated to refresh those certificates for now. It would make the logic a bit harder to check for this and I don't really see much of a benefit.
