### ISSUE TITLE
Please support http proxies for OCSP

### ISSUE THREAD

**Issue by bzed** [dehydrated-io/dehydrated#607]
Hi,

openssl does not respect the usual ALL_PROXY/HTTPS_PROXY environment variables.
Here is some example code that shows how to use proxies with openssl for requesting ocsp files:

https://github.com/bzed/bzed-letsencrypt/blob/master/templates/letsencrypt_get_certificate_ocsp.sh.erb

Thanks,
Bernd

**Comment by lukas2511** [comment]
If you really need this please submit a pull-request implementing this (also setting proxy for curl etc.). I've never had somebody else asking this and i think the suggested solution is a bit ugly... That might also cause issues with some OpenSSL versions as some don't support the header argument, which actually just recently caused issues with LibreSSL.
