### ISSUE TITLE
Operation to simply retrieve and output the Terms of Service URL

### ISSUE THREAD

**Issue by rg-sfs** [dehydrated-io/dehydrated#649]
I would like to be able to display the ToS URL of the configured ACME server without doing anything else. I realise it would be a fairly simple operation to implement as a separate script, however, it would be really nice if dehydrated could handle this directly without the need for additional code.

Is there any chance of a feature like this being added to a future version of dehydrated?

**Comment by lukas2511** [comment]
This has now been implemented in 7cc9e2d07f8f1a2a1144e0d865dbf8fec75806d3.
