### ISSUE TITLE
"keep going" suppresses the error status

### ISSUE THREAD

**Issue by rfc1036** [dehydrated-io/dehydrated#659]
When -g is used then the program will always return success, even when a domain fails.
This is inconvenient because then a calling script cannot know if some domains failed or not.

**Comment by kepi** [comment]
Its important to add that this is inconvenient for some but not for all. I.e. in our use case current behaviour is exactly what we want.

If there would be any changes, please consider adding different argument for new behavior.

**Comment by lukas2511** [comment]
This should be fixed now :)
