### ISSUE TITLE
dehydrated is not using the canonical Account URL

### ISSUE THREAD

**Issue by alexzorin** [dehydrated-io/dehydrated#671]
When you `dehydrated --register` a new ACMEv2 account, dehydrated correctly extracts the Account URL from the `Location` header in the registration response:

https://github.com/lukas2511/dehydrated/blob/018254974cb6cbf93ba9249b06b2d923e37a9e88/dehydrated#L414

However, on subsequent request (e.g. in `dehydrated -c`), dehydrated does not use that `ACCOUNT_URL`, and instead assumes that the account URL is constructed from the `newAccount` resource in the directory:

https://github.com/lukas2511/dehydrated/blob/018254974cb6cbf93ba9249b06b2d923e37a9e88/dehydrated#L421

In the case when you run against [Pebble](https://github.com/letsencrypt/pebble), this leads to a JWS error, because 

- the real account URL is e.g. `https://localhost:14000/my-account/8`, whereas 
- the account URL submitted by dehydrated is `https://localhost:14000/sign-me-up/8`.

**Comment by Rogdham** [comment]
Hi @alexzorin I was also trying to run against Pebble and found your issues, feel free to give #727 a test if you have some time  :blush:

**Comment by lukas2511** [comment]
Replaced by #727, will be fixed soon! Thanks!
