### ISSUE TITLE
Order finalization should check that the order is "valid" before trying to download the certificate

### ISSUE THREAD

**Issue by alexzorin** [dehydrated-io/dehydrated#673]
When dehydrated posts its CSR to the order finalization URL, it assumes that the certificate will be signed and immediately available for download in the response:

https://github.com/lukas2511/dehydrated/blob/018254974cb6cbf93ba9249b06b2d923e37a9e88/dehydrated#L870-L871

However, the order may be [in any number of states](https://tools.ietf.org/html/rfc8555#page-48) other than `valid`such as `processing`, where dehydrated should wait and poll until the certificate is ready for download.

Currently, dehydrated assumes the `certificate` field is always present which leads to an error. This error can be reproduced by running dehydrated against Pebble.

**Comment by Rogdham** [comment]
See #639 for a possible fix.

**Comment by lukas2511** [comment]
Fixed by #728, thanks.
