### ISSUE TITLE
Malformed account ID in KeyID header

### ISSUE THREAD

**Issue by rebeka-catalina** [dehydrated-io/dehydrated#677]
Hi - today wanted to register a new account and got this error
``{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Malformed account ID in KeyID header URL: \"https://acme-v02.api.letsencrypt.org/acme/acct/\"",
  "status": 400
}``

Then I searched for the problem and stumbled upon this thread:
https://community.letsencrypt.org/t/malformed-account-id-in-keyid-header-url-https-acme-v02-api-letsencrypt-org-acme-acct/99790

then I updated my version of dehydrated and the problem is still there.
Yesterday (before updating dehydrated) I could successfully do renewals for other vhosts on that system.

Did I miss something? Do I have to do something else than just updating dehydrated?

**Comment by lukas2511** [comment]
Did you update to git master or did you use a distro package? If the error persists with git master you could try moving your accounts directory and letting dehydrated register a new account. If you want to reuse the old account try removing `account_id.json` and edit `registration_info.json` and remove the `"id": "[...]",` line (if it exists).
