### ISSUE TITLE
remove tmp files after it have been used

### ISSUE THREAD

**Issue by j-ed** [dehydrated-io/dehydrated#681]
Today I checked the content of my /tmp folder and found a several files named "dehydrated-CAZeC3" etc. All contained the openssl.cnf files with some appended configuration lines:
```
...
[SAN]
subjectAltName=DNS: ...
1.3.6.1.5.5.7.1.31=critical,DER ...
```
It seems that the files are created in the `generate_alpn_certificate()` function but have not been removed afterwards.

**Comment by j-ed** [comment]
Create pull request to get this issue fixed: https://github.com/dehydrated-io/dehydrated/pull/745

**Comment by lukas2511** [comment]
Thanks! PR merged into jsonsh branch, will be merged to master soon(ish).
