### ISSUE TITLE
document $alias in hook script

### ISSUE THREAD

**Issue by hmoffatt** [dehydrated-io/dehydrated#687]
When the hook script is run, $alias contains the real name of the certificate directory in $CERTDIR. This is useful to know when the domain is a wildcard like "*.my.com", but as far as I can tell it's not documented anywhere.

**Comment by lukas2511** [comment]
I'm currently reworking the documentation and examples completely so I'm closing all issues and pull requests that only change those files, thanks anyway!

The "hidden" variables will be documented as well.
