### ISSUE TITLE
Dehydrated won't work with step-ca acme server / kid does not have required prefix

### ISSUE THREAD

**Issue by sigio** [dehydrated-io/dehydrated#689]
# dehydrated --config config-step -x -g  --signcsr some.csr 
# INFO: Using main config file config-step
 + Requesting new certificate order from CA...
  + ERROR: An error occurred while sending post-request to https://ca.int.cybersprint.nl/acme/acme/new-order (Status 400)

Details:
HTTP/2 400 
cache-control: no-store
content-type: application/problem+json
link: <https://my-internal-acme/acme/acme/directory>;rel="index"
replay-nonce: YVY5Z3VoVXZNWVhTRTVIYnVZQW9uR2N3Yk1RZk03Ylg
content-length: 246
date: Mon, 04 Nov 2019 12:31:09 GMT

{"type":"urn:ietf:params:acme:error:malformed","detail":"kid does not have required prefix; expected https://my-internal-acme/acme/acme/account/, but got https://my-internal-acme/acme/acme/new-account/TJtti927Rt3fyv5LRLRhaBgfs8oppRKI"}

The server I'm talking to does with with the acme.sh client and smallstep's own acme client.

**Comment by vidensky** [comment]
Problems with incorrect parsing of JSON. And a few other things.

I created a modification that works, but it's not pure code. The right solution is to go to the JSON parsing solution.

[dehydrated.zip](https://github.com/dehydrated-io/dehydrated/files/4160557/dehydrated.zip)

**Comment by lukas2511** [comment]
Closing this for now as this seems to be purely dependent on issue #516.
