### ISSUE TITLE
Support setting CA in per-certificate config (DOMAINS_D or certs/…)

### ISSUE THREAD

**Issue by alexs77** [dehydrated-io/dehydrated#697]
It would be very good, if it were possible to set the CA on a per-certificate level.

Example: for production domains, I'd like to use the "real" Let's Encrypt CA https://acme-v02.api.letsencrypt.org/directory
For test domains, I'd like to use the staging environment https://acme-staging-v02.api.letsencrypt.org/directory

According to https://github.com/lukas2511/dehydrated/blob/master/docs/per-certificate-config.md, the confguration variable `CA` cannot be changed in `certs/example.org/config` or `DOMAINS_D/example.org`.

**Comment by lukas2511** [comment]
This is not possible in the way dehydrated is currently structured. Closing this as it would require a major rewrite.
