### ISSUE TITLE
hook.sh and waiting for DNS records to propagate

### ISSUE THREAD

**Issue by basbebe** [dehydrated-io/dehydrated#709]
The deploy_challenge hook is being called once for every domain and alternative name.
I'm waiting 900s for each DNS record to propagate (safest with my provider).
At this point, this makes e.g. 900s x 4 if I have a certificate with three alternative names.

Is there a possibility for me to only wait once after all the records are created before the challenge?

Otherwise it would be nice to have an additional pre-challenge hook or the like…

**Comment by txr13** [comment]
You want to use HOOK_CHAIN: https://github.com/dehydrated-io/dehydrated/blob/master/docs/hook_chain.md

**Comment by basbebe** [comment]
yes I do!
thank you @txr13 
I don't know yet how to parse all the arguments though

**Comment by basbebe** [comment]
got it:
```

while [ $# -ne 0 ]; do

local DOMAIN="${1}" TOKEN_FILENAME="${2}" TOKEN_VALUE="${3}"
   
    ...

shift 3
done
```

**Comment by basbebe** [comment]
got it:
```

while [ $# -ne 0 ]; do

local DOMAIN="${1}" TOKEN_FILENAME="${2}" TOKEN_VALUE="${3}"
   
    ...

shift 3
done
```
