### ISSUE TITLE
multi-domains: behavior on failure to continue for each other entries

### ISSUE THREAD

**Issue by tst2005** [dehydrated-io/dehydrated#710]
Hello,

I'm using dehydrated 0.6.5, with http challenge.
My `domains.txt` file seems like :
```
example.com www.example.com server1.example.com
test.example.com
foo.example.com
service2.example.com
anotherdomain1.com www.anotherdomain1.com
anotherdomain2.com www.anotherdomain2.com
```

Everything is managed on one server named `server1.example.com`.
I'm working to migrate everything on `server2.example.com`.
I started by migrate one part. It took time.

I got an issue.
All the certificates needs to be renewed everything should be fine except one of the vhost (`foo.example.com`) that is move on the new server. The challenge produced by the `server1` is not found on `server2` by letsencrypt servers.

I used a simple workaround : comment the `foo.example.com` to renew all the other certificates.

The current behavior is "stop everything" on error.
I got:
```
- [x] OK: example.com www.example.com server1.example.com
- [x] OK: test.example.com
- [ ] FAILURE: foo.example.com
- [ ] nothing tried: service2.example.com
- [ ] nothing tried: anotherdomain1.com www.anotherdomain1.com
- [ ] nothing tried: anotherdomain2.com www.anotherdomain2.com
```

Feature/bug request:
- It is possible to have a behavior to continue after a failure to try to renew all certificates ? do not let expire certificates because of a neighbour has an issue.

**Comment by txr13** [comment]
Are you using the `--keep-going` flag?

See the parameter list under "Usage" on the main page:
```text
--keep-going (-g)                Keep going after encountering an error while creating/renewing multiple certificates in cron mode
```

**Comment by tst2005** [comment]
oh... I really missed this option ?!
It seems exactly what I needs !
but ... why it is not the default behavior ?

**Comment by txr13** [comment]
> but ... why it is not the default behavior ?

When you're using `--keep-going`, the script will continue normally. You'll need to review the cron logs or have some other way of verifying that your certificates were all renewed successfully. You won't have a non-zero exit code to indicate that the program terminated abonrmally.

**Comment by lukas2511** [comment]
Thanks @txr13. Closing this as it's solved :)

**Comment by tst2005** [comment]
Really ? dehydrated are unable to manage a simple global error status ?!
This option is a trap...

I implemented the behavior by myself.
```bash
#!/bin/sh
set -e
cd -- "$(dirname "$0")"

ERROR=0
[ -f all.domains.txt ] || cp -a dommains.txt all.domains.txt
while read -r line; do
        case "$line" in ('#'*) continue;; esac
        echo "$line" > domains.txt
        ./dehydrated-v0.6.5 --config config "${@:--c}" || ERROR=1
done < all.domains.txt
cp -a all.domains.txt domains.txt
exit $ERROR
```

Regards,
