### ISSUE TITLE
Beginning June 1, 2020, we will stop allowing new domains to validate using the ACMEv1 protocol

### ISSUE THREAD

**Issue by sadok** [dehydrated-io/dehydrated#711]
Hey.

What about the letter from LE about "Beginning June 1, 2020, we will stop allowing new domains to validate using the ACMEv1 protocol. You should upgrade to an ACMEv2 compatible client before then, or certificate issuance will fail." ?

Thanks.

**Comment by fbartels** [comment]
See https://github.com/dehydrated-io/dehydrated/blob/f60f2f81e89ad652aec91a5a86049a391513aa37/CHANGELOG#L41-L43

**Comment by metalefty** [comment]
If you've been using dehydrated before ACMEv2 is supported,  edit `config` file.

```diff
-CA="https://acme-v01.api.letsencrypt.org/directory"
+CA="https://acme-v02.api.letsencrypt.org/directory"
```

**Comment by sadok** [comment]
> ```diff
> -CA="https://acme-v01.api.letsencrypt.org/directory"
> +CA="https://acme-v02.api.letsencrypt.org/directory"
> ```
OK. I just tried first with 

`CA="https://acme-staging-v02.api.letsencrypt.org/directory"` 

and got the error 

`"detail": "No account exists with the provided key"`

"Dance" with

```
OLDCA="https://acme-staging.api.letsencrypt.org/directory"
OLDCA="https://acme-v01.api.letsencrypt.org/directory"
```

did not help. So I thought ...

The new one works, thanks.
