### ISSUE TITLE
incorrect indentation of output

### ISSUE THREAD

**Issue by x70b1** [dehydrated-io/dehydrated#713]
I get the following output for a `dehydrated` run:

```
Processing my-domain.com
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Jun  1 15:16:19 2020 GMT Certificate will not expire
(Longer than 30 days). Skipping renew!
 + OSCP stapling file is still valid (skipping update)
+ Running automatic cleanup
```

- "Longer than .." is printed on a new line
- There is a space missing in the last line before `Running`.

Actually only a very small problem, but maybe you want to fix it.
I haven't really looked into it yet. Probably just a combination of `echo` and `printf`.

**Comment by lukas2511** [comment]
Thanks, the issue was that the openssl expiry check simply printed "Certificate will not expire" on its own and that additionally appended the unwanted line break.
