### ISSUE TITLE
Is it possible to register with LetsEncrypt with an email address?

### ISSUE THREAD

**Issue by dave559** [dehydrated-io/dehydrated#719]
Is it possible to use dehydrated to register with LetsEncrypt with an email address (rather than just anonymously)?

LetsEncrypt will send warning emails to accounts registered with an email address if, for some reason, a cert hasn't been renewed close to the expiry date, which could be a useful feature to make use of in the event that something goes wrong with the automated processes on one's webserver.

I can see that there is an `--account` option, but I can't see any instructions about how to use it?

**Comment by jobe1986** [comment]
The --account option updates the account information Let's Encrypt has from what is specified in the config file, you can specify the email address in the config file.

The config file is simply a file named "config" created from docs/examples/config in the same directory as the dehydrated script.

**Comment by dave559** [comment]
Thanks, jobe1986.

Just to elaborate, there is a `CONTACT_EMAIL=` setting (which is unset by default) in the `config` file, which the site admin can uncomment and then append the appropriate email address to, and then run `dehydrated --account` for that setting to be updated.

It is also possible to add this setting to a local config file in the `conf.d` folder, which may be an easier way to do this for our automated server configuration setup.
