### ISSUE TITLE
Example ngnix configuration on the main page is wrong!

### ISSUE THREAD

**Issue by kobaz** [dehydrated-io/dehydrated#723]
`
stream {
  server {
    map $ssl_preread_alpn_protocols $tls_port {
      ~\bacme-tls/1\b 10443;
      default 443;
    }

    server {
      listen 443;
      listen [::]:443;
      proxy_pass 10.13.37.42:$tls_port;
      ssl_preread on;
    }
  }
}

This is invalid ngnix syntax.
Proper example:
stream {
    map $ssl_preread_alpn_protocols $tls_port {
      ~\bacme-tls/1\b 10443;
      default 4443;
    }

    server {
      listen 443;
      listen [::]:443;
      proxy_pass 127.0.0.1:$tls_port;
      ssl_preread on;
    }
}

`

**Comment by lukas2511** [comment]
I'm currently reworking the documentation and examples completely so I'm closing all issues and pull requests that only change those files, thanks anyway!
