### ISSUE TITLE
Account base64 representation is calculated with "\n"

### ISSUE THREAD

**Issue by domrim** [dehydrated-io/dehydrated#730]
Hi, at first: Thanks for this great piece of software :)

i stumbled upon a small issue with the account urlbase64 creation. the issue is in line 233 and 236 where `CAHASH` and `OLDCAHASH` are created:
https://github.com/dehydrated-io/dehydrated/blob/dbb0ef1ce1a93a20fe1cc532adbdf676cb14c3d3/dehydrated#L232-L244

because the CA-String gets echoed with `echo ${CA}` and not `echo -n {CA}"` the actual string which gets Base64 encoded is "https://acme-v02.api.letsencrypt.org/directory\n" instead of "https://acme-v02.api.letsencrypt.org/directory" (for the default `${CA}` value).

I don't know if this issue is fixable because it would require to rename the account folder for all existing users, but i wanted to let you know of the issue. I also wouldn't see this as a large issue, it just fell on my feet when i wanted to calculate the base64 string within python.

**Comment by lukas2511** [comment]
Yea this is something I'll just leave as is since it's not really disturbing operation, maybe I'll sneak in a little note for developers with the next commit ;) Thanks for reporting!
