### ISSUE TITLE
Issue with two domains (master.tld *.master.tld) on same TXT record

### ISSUE THREAD

**Issue by toblery** [dehydrated-io/dehydrated#732]
Hi

I have one domain and I would create one certificate with master domain (without hostname part) and asterisk domain. I am also using a web hook to create DNS entries but when challenge/responses are being set, it's done one at a time.
First it creates challenge for _acme-challenge.master.tld for master.tld
Second it creates challenge for _acme-challenge.master.tld for *.master.tld
So it overwrites first created TXT record and then goes to Letsencrypt verification process which sees only second challenge.

Is it a bug on my own hook script not to delete first TXT record or is it working as intended?
Does Letsencrypt understand if there are two TXT records for _acme-challenge host?

Regards, Henri

**Comment by lukas2511** [comment]
Please see https://github.com/dehydrated-io/dehydrated/blob/master/docs/troubleshooting.md#dns-invalid-challenge-since-dehydrated-060--why-are-dns-challenges-deployed-first-and-verified-later

Both TXT records should be deployed at the same time.
