### ISSUE TITLE
add hook for propagate_challenge

### ISSUE THREAD

**Issue by jeffgoh** [dehydrated-io/dehydrated#744]
Whilst I can add a wait for each challenge to propagate, if I have say 10 challenges, that's 10 DNS propagations to wait for, which is inefficient.  Much more efficient to add one more hook for propagate_challenge.  Will file a pull request shortly.

**Comment by c-MM** [comment]
I use HOOK_CHAIN="yes" to get all challenges at once and deploy them. Maybe this is what you need?

**Comment by lukas2511** [comment]
Use HOOK_CHAIN and configure your hook script to wait for challenge propagation. Any other way is either already solvable in hook scripts, or would break order of operations which is important for a lot of setups.
