### ISSUE TITLE
SAN error generating cert for CNAME domain

### ISSUE THREAD

**Issue by drlauridsen** [dehydrated-io/dehydrated#746]
Sorry if this is not the right place to ask this question, and I am a complete newbie 🙂, so this question might seem stupid..

I use nginx on my router.
I have successfully used dehydrated and generated a certificate for a subdomain supplied by asus together with my router, eg name.asuscomm.com.
I have some  subdomains as CNAME on my own domain with my webhost (not my own server..) eg subd.hosteddomain.com - which then points to name.asuscomm.com.

When trying to generate certificates for these cname subdomains, I get the following error..

----
```
bash ./dehydrated --domain subd.hosteddomain.com  --cron
# INFO: Using main config file /opt/etc/nginx/config
Processing subd.hosteddomain.com
 + Signing domains...
 + Generating private key...
 + Generating signing request...
Error Loading request extension section SAN
```
---
What am I doing wrong?

**Comment by danimo** [comment]
Please post the output of `dehydrated --version`.

**Comment by danimo** [comment]
The openssl version on your asus router might be old or custom built. Can you also provide the output of `openssl version` and the contents of `/etc/ssl/openssl.cnf` (might be `/etc/openssl.cnf` alternatively)?

**Comment by lukas2511** [comment]
This seems to be an issue with a weird openssl version. Seeing this as out-of-scope for dehydrated.
