### ISSUE TITLE
moving a domain between servers

### ISSUE THREAD

**Issue by robo2bobo** [dehydrated-io/dehydrated#749]
I'm using dehydrated on two servers. I would like to move a domain hosted from server A, to server B. From the documentation, its not clear if its enough to just move the 'certs/domain' and 'archive/domain' directories along with the domains.txt entry. The two servers use different let's encrypt accounts.

Could you please add some notes about moving domains or a general note about the portability of dehydrated controlled domains.

Thank you.

**Comment by lukas2511** [comment]
You just copy your configuration, entries from domains.txt and the parts of the certs subdirectory you want to move, that's all. I don't understand what the problem is. Dehydrated doesn't "manage" any domains, it just queries ACME APIs for certificates and provides required validation tokens.

**Comment by txr13** [comment]
Further to what @lukas2511 said...

Dehydrated does not “control” domains, even for the purposes of issuing certificates. You mentioned that the two servers use different LE accounts, which makes me think you may be under the impression that dehydrated sort of “ties” domains to LE accounts. That doesn’t happen with LE certificate issuance—any LE account can request any certificate for any domain at any time. Therefore there is no need for any “migration” process—copying the relevant configuration (and optionally any existing certificates) is sufficient.

**Comment by robo2bobo** [comment]
Maybe "control" was not the right word to use.

Thank you @txr13, you answered my question in full.
