### ISSUE TITLE
Allow multiple domains.txt in a domains.txt.d directory

### ISSUE THREAD

**Issue by Zocker1999NET** [dehydrated-io/dehydrated#750]
Like other .d directories, e.g. `/etc/apt/sources.list.d`.
This may could be added easily by `cat`-ing all files in such directory if given before interpreting the domains.

**Comment by lukas2511** [comment]
Don't really like this. If you need this it should be easily implemented using a wrapper script, especially now that setting the path to domains.txt via cli argument is supported.
