### ISSUE TITLE
failed to parse Keyfile

### ISSUE THREAD

**Issue by astrakid** [dehydrated-io/dehydrated#755]
hi,
i am new to dehydrated, took over a project from another one, who installed dehydrated in 2018, but i am not sure if it ever worked.
however the project seems very cool.
when executing dehydrated i get the error message

 + Deploying challenge tokens...
;; ERROR: failed to parse keyfile '/etc/bind/Kdns_key.+199+29807.private'
ERROR: deploy_challenge hook returned with non-zero exit code

the file is readable:

root@xxx:/etc/dehydrated# cat /etc/bind/Kdns_key.+199+29807.private 
Private-key-format: v1.3
Algorithm: 157 (HMAC_MD5)
Key: EmPuJtE1uUtgaFT52KRQ6yleAUOsoEdRa4L5l6qLJyrq5AN89dM2MhsMnYWJfKbod8oRvIcJ+JhhqsvZSX94Dg==
Bits: AAA=
Created: 20190112184055
Publish: 20190112184055
Activate: 20190112184055

whoat am I missing?

**Comment by lukas2511** [comment]
This is an error reported by your hook script, not by dehydrated itself.
