### ISSUE TITLE
Request: Insert affected domain in error message for unsuccessful API call

### ISSUE THREAD

**Issue by movd** [dehydrated-io/dehydrated#757]
It would be useful if the affected FQDN would also be printed if an error message was issued due to an unsuccessful API call "ERROR: An error occurred while sending...".

https://github.com/dehydrated-io/dehydrated/blob/master/dehydrated#L718

**Comment by danimo** [comment]
Do you have a case where it fails for one domain and not for another? Currently dehydrated always communicates with the same CA for all domains. It should always fail and if not, it should be due to an unreliable network, not due the domain.

**Comment by movd** [comment]
Hi, thanks for getting back to me. It took a while for the problem to reappear in production.  Last night dehydrated took care of renewing 156 certificates with 398 challenge responses (often multiple SANs). The whole process took around one hour (which is fine by me).

From this quite big batch, there was one error:

```sh
  + ERROR: An error occurred while sending post-request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/8365901279/LW-JSQ (Status 500)

Details:
HTTP/1.1 100 Continue

HTTP/1.1 500 Internal Server Error
Server: nginx
Date: Wed, 04 Nov 2020 21:55:13 GMT
Content-Type: application/problem+json
Content-Length: 174
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 00036cdHAqT4YhEVvs1JabTxSQjc3cKR_XVw5VH9SbTzAVY

{
  "type": "urn:ietf:params:acme:error:serverInternal",
  "detail": "Error retrieving account \"https://acme-v02.api.letsencrypt.org/acme/acct/21979153\"",
  "status": 500
}
```

This is not a pressing issue, but it would be nice to know where this problem appeared.  _Also, we should create smaller renewal batches..._

**Comment by lukas2511** [comment]
I'm not really seeing what's missing here? Just read up 3 lines of your logfile where it states "Responding to challenge for $fqdn authorization..." just before the error occurs?
