### ISSUE TITLE
Way to accomodate multiple CAs

### ISSUE THREAD

**Issue by darix** [dehydrated-io/dehydrated#762]
I have one machine which uses LE for external certs and step CA for internal certificates.

Having an instantiated service in systemd makes this relatively simple to start dehydrated
with a different config file. But before we implement it I was wondering how we want to go about it

e.g. the unit file has

```
ExecStartPost=-/usr/bin/find -L /etc/dehydrated/postrun-hooks.d -maxdepth 1 -executable -type f -exec {} \;
ExecStart=/usr/bin/dehydrated --cron
```

The first part is easy:

```
ExecStart=/usr/bin/dehydrated --cron --config /etc/dehydrated/%i.conf
```

Should the instantiated service then keep using the shared postrun-hooks.d? or something like

```
ExecStartPost=-/usr/bin/find -L /etc/dehydrated/postrun-hooks-%i.d -maxdepth 1 -executable -type f -exec {} \;
```

do we want to have completely different config directories and just do:

```
ExecStartPost=-/usr/bin/find -L /etc/dehydrated-%i/postrun-hooks.d -maxdepth 1 -executable -type f -exec {} \;
ExecStart=/usr/bin/dehydrated --cron --config-dir /etc/dehydrated-%i
```

This would also avoid potential conflicts when both configs/domain.txt specify the same output filename.

**Comment by lukas2511** [comment]
Tbh I think this is something you have to decide for yourself. I have no insight in your particular setup and in some cases it might make sense to reuse hooks, in others it might completely differ.

**Comment by darix** [comment]
Well some of the problems could be made a lot easier if the code is already written with the multi CA handling in mind.

**Comment by lukas2511** [comment]
> Well some of the problems could be made a lot easier if the code is already written with the multi CA handling in mind. And if this would be an upstream feature then all distros would use the same code for this and not everyone inventing their own.

That would require really big changes in dehydrated, rewriting a lot of the loop logic.
Since I don't see much use of this feature for most users I think it'd easier if the very few people who need it just use a wrapper like you are seemingly trying to do.

**Comment by darix** [comment]
well other options would be to have e.g. --config-dir option ... then we wouldnt need (cmdline) options for each and every file. that would make the whole process a lot easier already.

**Comment by jobe1986** [comment]
> well other option would be to have e.g. --config-dir option ... then we wouldnt need (cmdline) options for each and every file. that would make the whole process a lot easier already. I dont expect the whole multi CA thing implemented within dehydrated. but making the cmdline interface easier to launch it multiple times

There is a  "--config" (-f) option for specifying the path to a specific config file, in which you can configure various directories, including BASEDIR which would allow you to achieve the same goal.
