### ISSUE TITLE
EXPECTED value GOT EOF

### ISSUE THREAD

**Issue by Zverushko** [dehydrated-io/dehydrated#763]
Hello

i get this err:
Processing fancy-group.ru with alternative names: www.fancy-group.ru
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Oct  3 12:41:40 2018 GMT (Less than 20 days). Renewing!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting authorization for fancy-group.ru...
EXPECTED value GOT EOF

worked fine for several years before

**Comment by Zverushko** [comment]
remove get_json_dict_value validationRecord from 1004 line solved the issue

**Comment by lukas2511** [comment]
Can you maybe add some debug printing around that line? e.g. `echo "${challenge}"` right before. It's old ACME v1 code that is hard to maintain, so it would be nice to know what exactly is going wrong.

**Comment by Zverushko** [comment]
+ Requesting authorization for fancy-group2.ru...
  + ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-authz (Status 403)

Details:
HTTP/1.1 100 Continue

HTTP/1.1 403 Forbidden
Server: nginx
Date: Tue, 15 Sep 2020 12:36:41 GMT
Content-Type: application/problem+json
Content-Length: 230
Connection: keep-alive
Boulder-Requester: 37829745
Cache-Control: public, max-age=0, no-cache
Replay-Nonce: 0002JJLmO8FyzQMCdQ-wfiIX3GByYpYvKynIQnxExSak0EE

{
  "type": "urn:acme:error:unauthorized",
  "detail": "Error creating new authz :: Validations for new domains are disabled in the V1 API (https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430)",
  "status": 403
}

EXPECTED value GOT EOF

**Comment by lukas2511** [comment]
Well, there is your problem. The ACME v1 API has been deprecated, you need to upgrade dehydrated and switch over to the ACME v2 API. I should probably try to catch that error. Closing this issue as the actual problem is just using the deprecated API.

**Comment by Zverushko** [comment]
i think the message "EXPECTED value GOT EOF" - not what i need to get=)

**Comment by lukas2511** [comment]
I pushed a tiny change that should print the message from the CA instead of failing in json parsing.

**Comment by matthewhegarty** [comment]
For anyone seeing this in future, it could be disruption on server-side.

- Has just failed with the error below (have already run it once and got the same error)
- checked  https://letsencrypt.status.io/ - this reports that there is service disruption on the server side

![le-disruption](https://user-images.githubusercontent.com/6249838/124187060-1f0fd880-dab5-11eb-82af-a4be4c07e52d.png)

```
 + Requesting certificate...
  + ERROR: An error occurred while sending post-request to https://acme-v02.api.letsencrypt.org/acme/finalize/128796371/10782289964 (Status 500)

Details:
HTTP/2 500 
server: nginx
date: Thu, 01 Jul 2021 20:33:34 GMT
content-type: application/problem+json
content-length: 112
boulder-requester: 128796371
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
replay-nonce: 0102HllxQb618Pa9KKZwjWOhKlgW_yGflbdcMgH31nCAMf8

{
  "type": "urn:ietf:params:acme:error:serverInternal",
  "detail": "Error finalizing order",
  "status": 500
}

EXPECTED value GOT EOF
```
