### ISSUE TITLE
cURL error 3

### ISSUE THREAD

**Issue by Glujaz** [dehydrated-io/dehydrated#768]
Hello,

I am trying to make renewing my certificates working again.
I'm running on Mac OS Server, and using this for automatic update, and work like a charm for years.
[Letsencrypt-mac](https://github.com/physcip/letsencrypt-macl)

The thing is, that it's not working anymore for about a month now.
And after pinpointing stuff, it seems to be coming from Dehydrated : 

as it is with the dehydrated command the error appears : 

dehydrated/dehydrated --cron --hook ./hooks.sh --domain files.example.fr

And the error : 

# INFO: Using main config file /usr/share/letsencrypt-mac/config
+ Fetching account URL...
ERROR: Problem connecting to server (head for ; curl returned with 3)
ERROR: Problem connecting to server (post for ; curl returned with 3)

Error 3 seems to be coming from a bad syntax, but I simply can't find where the cURL input location comes from...

The hooks can be found here : 

https://github.com/physcip/letsencrypt-mac/blob/master/hooks.sh

Thanks in advance

**Comment by Glujaz** [comment]
Ok, it seems to be a problem with the 0.6.8 version. I managed to find an older one which worked : the 0.6.5.
Replaced it for now.

**Comment by lukas2511** [comment]
I think this is the same issue that was reported in #756 and should be fixed in current master branch. Will do a new release in the coming days.
