### ISSUE TITLE
Request for retry loop for resiliency against curl error 35

### ISSUE THREAD

**Issue by morganwdavis** [dehydrated-io/dehydrated#769]
When this error occurs during a cron run:

```
# INFO: Using main config file /usr/local/etc/dehydrated/config
ERROR: Problem connecting to server (get for https://acme-v02.api.letsencrypt.org/directory; curl returned with 35)
```

...it seems to be some kind of intermittent problem with a glitchy LE server that came up in round-robin.

Perhaps a **configurable sleep-and-retry loop** (N times before giving up) could easily resolve that.

This actually bit me because I assumed that these connections would just always work. I had cron set up to run dehydrated on the first of each month, figuring that if certs expire in 90 days, running once every 30 days or so should be fine. But a failed run one month would put me beyond the 10-day renewal window and some certs would expire.  It happened a couple of times before I figured out that the cron runs would fail. Now I have it changed to run via cron daily. Sure, it works when tomorrow's run happens, but just retrying today would likely avoid this.

Thanks for considering.

**Comment by lukas2511** [comment]
Hi. I'm aware of those issues and was asked for retry logic in a few tickets before. I've decided to close them all and consolidate them into a single issue which can be found here: #792. Thanks for reporting.
