### ISSUE TITLE
Unknown hook sync-cert

### ISSUE THREAD

**Issue by burl23** [dehydrated-io/dehydrated#772]
I ran dehydrate -c and got some error messages that it said to ignore until I got the message unknown hook syn-cert.  Here are the messages I received:

beryl@rock64:~/dehydrated$ ./dehydrated -c
# INFO: Using main config file /home/beryl/dehydrated/config
Unknown hook this_hookscript_is_broken__dehydrated_is_working_fine__please_ignore_unknown_hooks_in_your_script
 + Creating chain cache directory /home/beryl/dehydrated/chains
Processing rock64ha.duckdns.org
 + Creating new directory /home/beryl/dehydrated/certs/rock64ha.duckdns.org ...
Unknown hook this_hookscript_is_broken__dehydrated_is_working_fine__please_ignore_unknown_hooks_in_your_script
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for rock64ha.duckdns.org
 + 1 pending challenge(s)
 + Deploying challenge tokens...
OK
 + Responding to challenge for rock64ha.duckdns.org authorization...
 + Challenge is valid!
 + Cleaning challenge tokens...
OK
 + Requesting certificate...
 + Checking certificate...
 + Done!
 + Creating fullchain.pem...
Unknown hook sync_cert
[sudo] password for beryl:
Failed to restart home-assistant@homeassistant.service: Unit home-assistant@homeassistant.service not found.
ERROR: deploy_cert hook returned with non-zero exit code

Now I apparently don't have a !secret file so configuration.yaml won't load.  What can I do?

**Comment by lukas2511** [comment]
This is not a dehydrated issue, this is an issue with your hook script and/or the software you are using.
The hooks in the wiki are user supplied and I'm not providing any kind of support for those.

**Comment by burl23** [comment]
Thank you for the advice to look at the hook script.  After a while I found the error and everything is good now.

Sent from Mail for Windows 10
