### ISSUE TITLE
Upcoming intermediate transition

### ISSUE THREAD

**Issue by jcharaoui** [dehydrated-io/dehydrated#774]
As per a recent Let's Encrypt [announcement](https://letsencrypt.org/2020/09/17/new-root-and-intermediates.html), in a few weeks there will be a certificate [transition](https://community.letsencrypt.org/t/detailed-2020-hierarchy/131019/3) that should result in a change from the current default fullchain of `leaf+x3` to `leaf+e1+x2-signed-by-x1`. I'm wondering if dehydrated will handle that switch gracefully? Thanks.

**Comment by lukas2511** [comment]
Dehydrated gets the certificate chain from the CA for each order, so this change will probably not have any impact and it will simply use the new chain.
