### ISSUE TITLE
Option to continue fetching certificate if some alternative names don't work

### ISSUE THREAD

**Issue by thegushi** [dehydrated-io/dehydrated#781]
Hey there

It would be useful to have an option to continue fetching a certificate if not all alternative names work.  Sometimes multiple domains point to a single vhost, and if one of them expires it would be good to still get a cert for the remaining, valid, names.

For this purpose, I would typically use a challenge which will always pass as the "main" domain name.

From the looks of the way dehydrated works, this would probably require restarting the issuance process for a given cert, only for alternatives which have passed the challenges.

My specific use case is that when I give a person a domain name to use, I want to be able to fire up lets-encrypt with *something*, even if their domain name is not pointing at my server yet, so I create a private name (like theirtempsite.myhostingco.com).

**Comment by lukas2511** [comment]
This will not really work. The signing request is generated before any validation starts. If any domain is not validated the certificate order will fail completely.
