### ISSUE TITLE
New release 0.7.0 ?

### ISSUE THREAD

**Issue by mapreri** [dehydrated-io/dehydrated#786]
Hi,

I've been asked whether there is a plan to cut a new release.  Is there any rough timeline at this time?

I assume you plan on first taking care of https://github.com/dehydrated-io/dehydrated/milestone/3 ?

Thanks for taking care of dehydrated for all of us! :heart:

**Comment by lukas2511** [comment]
Hi,

I renamed the milestone to "things I'd like to get done but uhm, not now" to make it a bit clearer that I'm not really updating those milestones anymore (maybe I should...)

I'll probably be doing a release next week.

.@danimo has been kicking me again and again for the past few weeks to finally release a new version :see_no_evil:
I'm now at the point where I think the JSONsh integration to be stable (not really any complaints other than some weird old busybox system) and some other features have also been integrated. There are a few more minor patches that I want to look into, but if they turn out to be bigger issues I'll let them be for a more minor release shortly after.

**Comment by lukas2511** [comment]
This has been fixed in 082da2527cb4aaa3a4740ba03e550205b076f822 ;)
