### ISSUE TITLE
certificate-specific config does not work with values containing space

### ISSUE THREAD

**Issue by zhangyoufu** [dehydrated-io/dehydrated#789]
```
PREFERRED_CHAIN='DST Root CA X3'
```
failed with
```
ERROR: Alternative chain with CN = 'DST Root CA X3' not found, available options: DST Root CA X3, ISRG Root X1
```

The parsing logic for certificate-specific config does not handle quotes correctly. See
https://github.com/dehydrated-io/dehydrated/blob/589e9f30b383751a927d745e83c0c53bf42a195c/dehydrated#L1600-L1627

**Comment by lukas2511** [comment]
I tried a simpler fix first, which seemed at least a tiny bit cleaner on first sight. I should find a better way for doing these checks...

**Comment by zhangyoufu** [comment]
Trim single quotes from config_value does fix the issue for my use case. I'm looking forward to a better way.

```
$ FOO="'"
$ set | fgrep FOO=
FOO=\'
```
