### ISSUE TITLE
Challenge validation has failed when running with cron

### ISSUE THREAD

**Issue by cdarken** [dehydrated-io/dehydrated#793]
This happened suddenly, no idea what the issue can be, as it runs fine when I'm invoking it manually.
Using http-01 challenge type.

**Comment by j-ed** [comment]
Without providing the DETAILED output of the script it won't be possible to identify the root cause of the problem. Please update your positing and provide the missing information.

**Comment by cdarken** [comment]
How do you suggest to get it? I only have the redirected output to a file. Can't see any detailed log switch to the script.
I only have this, for the last failed run:
```
Processing [domain_name]
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Dec 20 22:00:42 2020 GMT (Less than 10 days). Renewing!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for [domain_name]
 + 1 pending challenge(s)
 + Deploying challenge tokens...
 + Responding to challenge for [domain_name] authorization...
 + Cleaning challenge tokens...
 + Challenge validation has failed :(
```

**Comment by cdarken** [comment]
So I just caught another output like that in the server log. I modified the cron to execute it in the next minute to check the output and now it worked! Any other ideas?

**Comment by hnnweb** [comment]
What did you change ?

( To be helpful upon others, you should provide every step you did to help the community )

**Comment by cdarken** [comment]
Change from what? From the previous run when it failed?

**Comment by lukas2511** [comment]
This may just be related to some Let's Encrypt downtimes. I recommend checking their status page at https://letsencrypt.status.io if this happens again.

**Comment by cdarken** [comment]
Thanks! I remember I saw recently some social media posts about their new hardware. Maybe it was due to the limitations of their old servers.
