### ISSUE TITLE
Can't get new cert

### ISSUE THREAD

**Issue by vintury** [dehydrated-io/dehydrated#794]
Hello.
Previously i use dehydrated script for generate new cert's.
Few days ago i see that script not worked.

I have error:
````
 $ ./dehydrated --register --accept-terms
# INFO: Using main config file /path/letsencrypt-mydomain.com/config
+ Generating account key...
+ Registering account key with ACME server...
+ Fetching account ID...
+ Done!
$ ./dehydrated -c
# INFO: Using main config file /path/letsencrypt-mydomain.com/config
 + Creating chain cache directory /path/letsencrypt-mydomain.com/chains
Processing *.mydomain.com
 + Creating new directory /path/letsencrypt-mydomain.com/certs/star_mydomain_com ...
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for mydomain.com
 + 1 pending challenge(s)
 + Deploying challenge tokens...
Error: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
Could not find zone for mydomain.com
````

How i can fix this problem?

**Comment by j-ed** [comment]
>  + Deploying challenge tokens...

>  Error: NoCredentialProviders: no valid providers in chain. Deprecated.
> 	   For verbose messaging see aws.Config.CredentialsChainVerboseErrors

Based on that message I believe that your challenge deployment script causes the error. which has nothing to do with dehydrated itself. If you search the internet for that error you find several related threads:

https://www.google.com/search?client=firefox-b-d&q=NoCredentialProviders%3A+no+valid+providers+in+chain.+Deprecated.

**Comment by lukas2511** [comment]
This definitively looks like an issue with your hook script. Not a dehydrated issue.
