### ISSUE TITLE
Feature request: Wait Time

### ISSUE THREAD

**Issue by ambergerit** [dehydrated-io/dehydrated#799]
Hello, by signing via DNS Server somtimes challenge fails, because the entry isn't published wide enough. Normally dehydrated asks google dns if TXT Record is published, bevore going on. Sometimes the LE Servers say "couldn't find TXT record" and challenge fails. So is there a option to put a new config value in config file e.g. /etc/dehydrated/config where i could set the first wait time to propagation of the DNS records?

Behaviour: 
default 0 after google answers
configureable "XX" seconds to wait for all DNS based challenges bevore first request is done at LE to get more time to propagate the TXT-Record

**Comment by jobe1986** [comment]
This has been requested on numerous occasions and it was decided that this is a job for the hook script providing the DNS updates. Specifically it was determined that the hook script should make an effort to ensure the DNS update has completed before returning from the deploy_challenge hook.

**Comment by ambergerit** [comment]
maybe, but in some cases it didn't work, or it should be changed to set the first default wait value to e.g. 30 seconds

**Comment by lukas2511** [comment]
Again and again... Making sure that DNS changes have successfully been rolled out is a task left to the hook script. I'll not be adding any delays here. If your DNS validations are failing your hook script is not working correctly.
