### ISSUE TITLE
Bug reading nonce data from headers

### ISSUE THREAD

**Issue by joele89** [dehydrated-io/dehydrated#802]
bug on F5 v13 (curl 7.47.1) where curl will not have spaces between header name and content. results in empty nonce variable.

\# INFO: Using main config file /shared/letsencrypt/config
\+ Generating account key...
\+ Registering account key with ACME server...
  \+ ERROR: An error occurred while sending post-request to https://acme-staging-v02.api.letsencrypt.org/acme/new-acct (Status 400)

Details:
HTTP/2.0 400
server:nginx
date:Mon, 22 Feb 2021 08:12:33 GMT
content-type:application/problem+json
content-length:112
cache-control:public, max-age=0, no-cache
link:<https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
replay-nonce:00032j5SQTM3vKzMqhzyW6r4AH7qJNDWVNjqg-AaT41pFyM

{
  "type": "urn:ietf:params:acme:error:badNonce",
  "detail": "JWS has no anti-replay nonce",
  "status": 400
}

**Comment by lukas2511** [comment]
Hi, Thanks for bringing this up.
I've merged your pullrequest, but also rewrote it a minute later while fixing similar issues in the script. Really weird behaviour with the lowercase headers and no whitespace...
