### ISSUE TITLE
Silly question: How does one install dehydrated?

### ISSUE THREAD

**Issue by contentfree** [dehydrated-io/dehydrated#807]
I read through the domains_txt.md and the Usage wiki but neither mention how to actually _install_ dehydrated.

**Comment by lukas2511** [comment]
One does not simply install dehydrated.. Jokes aside: There isn't anything to install. Dehydrated is a simple shell script. Download the script, make it executable using `chmod +x dehydrated` or invoke it using `bash dehydrated` and it just works. Alternatively there are packages for SUSE, Debian and some other distros, but they sometimes lag a version or two behind.
