### ISSUE TITLE
DEHYDRATED_USER + --signcsr sends certificate output to stderr

### ISSUE THREAD

**Issue by taam** [dehydrated-io/dehydrated#816]
`command_sign_csr` first does some IO redirection, then calls `init_system`, which might call `sudo`:
https://github.com/dehydrated-io/dehydrated/blob/5c1551e946456f534cf46b6ebabe4353bf0b0530/dehydrated#L1762-L1767

Solution might be as easy as calling `init_system` before doing the redirects, but I don't know the internals.

**Comment by lukas2511** [comment]
Thx. I swapped the lines as suggested.

This will result in some informational messages being output to stdout as well, but that should be less of a problem as there was additional output before anyway and PEM format should ignore anything outside BEGIN/END blocks.
