### ISSUE TITLE
After upgrade to v2, I cannot sign certs anymore.

### ISSUE THREAD

**Issue by jmgurney** [dehydrated-io/dehydrated#818]
I just recently upgrade to ACMEv2, and I'm now getting this error message when attempting to sign existing certs that worked under v1:
```
 + Valid till May 28 11:15:46 2021 GMT (Longer than 30 days). Ignoring because renew was forced!
 + Signing domains...
ERROR: Certificate authority doesn't allow certificate signing
```

I attempted to switch back to v1 to ensure that I'd have working certs, but now I get:
```
 + Generating signing request...
 + Requesting authorization for xxxx.yyyy...
EXPECTED value GOT EOF
```

This is w/ dehydrated 0.7.0.

**Comment by lukas2511** [comment]
I'm really not sure what you are doing. You give no information about your configuration and expect your issues to be magically solved?

**Comment by jmgurney** [comment]
Can you please fix up the documentation/error messages wrt to switching to v2?  It turns out that I have an old/original config file that has `API=1` set in it and w/o any documentation or helpful error messages, I wasted hours of my time trying to figure it out.

https://twitter.com/encthenet/status/1383944449508601858?s=20
