### ISSUE TITLE
Challenge validation has failed 

### ISSUE THREAD

**Issue by kshah37** [dehydrated-io/dehydrated#819]
Hi, I am trying to renewing my let's encrypt dehydrated certificated by running ./letsencrypt .sh script.

But, It gives me this error. Some how it's not putting the validating challenge in to the directory.  So it gives me http-01 error. 

root@fusionpbx:/usr/src/fusionpbx-install.sh/debian/resources# ./letsencrypt.sh
Domain Name: lab.smartipcloud.com
Email Address: tfernnadez@smartip.ca
fatal: destination path 'dehydrated' already exists and is not an empty directory.
# INFO: Using main config file /etc/dehydrated/config
+ Account already registered!
# INFO: Using main config file /etc/dehydrated/config
Processing lab.smartipcloud.com
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till May  3 12:38:03 2021 GMT (Less than 30 days). Renewing!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for lab.smartipcloud.com
 + 1 pending challenge(s)
 + Deploying challenge tokens...
 + Responding to challenge for lab.smartipcloud.com authorization...
 + Cleaning challenge tokens...
 + Challenge validation has failed :(
ERROR: Challenge is invalid! (returned: invalid) (result: ["type"]      "http-01"
["status"]      "invalid"
["error","type"]        "urn:ietf:params:acme:error:connection"
["error","detail"]      "Fetching http://lab.smartipcloud.com/.well-known/acme-challenge/fldIKdGzgAEWBsKn0UVC4Q_fwk3zrq8o8QUg2cTrfqU: Timeout during connect (likely firewall problem)"
["error","status"]      400
["error"]       {"type":"urn:ietf:params:acme:error:connection","detail":"Fetching http://lab.smartipcloud.com/.well-known/acme-challenge/fldIKdGzgAEWBsKn0UVC4Q_fwk3zrq8o8QUg2cTrfqU: Timeout during connect (likely firewall problem)","status":400}
["url"] "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12460660075/zDKxIw"
["token"]       "fldIKdGzgAEWBsKn0UVC4Q_fwk3zrq8o8QUg2cTrfqU"
["validationRecord",0,"url"]    "http://lab.smartipcloud.com/.well-known/acme-challenge/fldIKdGzgAEWBsKn0UVC4Q_fwk3zrq8o8QUg2cTrfqU"
["validationRecord",0,"hostname"]       "lab.smartipcloud.com"
["validationRecord",0,"port"]   "80"
["validationRecord",0,"addressesResolved",0]    "159.203.20.180"
["validationRecord",0,"addressesResolved"]      ["159.203.20.180"]
["validationRecord",0,"addressUsed"]    "159.203.20.180"
["validationRecord",0]  {"url":"http://lab.smartipcloud.com/.well-known/acme-challenge/fldIKdGzgAEWBsKn0UVC4Q_fwk3zrq8o8QUg2cTrfqU","hostname":"lab.smartipcloud.com","port":"80","addressesResolved":["159.203.20.180"],"addressUsed":"159.203.20.180"}
["validationRecord"]    [{"url":"http://lab.smartipcloud.com/.well-known/acme-challenge/fldIKdGzgAEWBsKn0UVC4Q_fwk3zrq8o8QUg2cTrfqU","hostname":"lab.smartipcloud.com","port":"80","addressesResolved":["159.203.20.180"],"addressUsed":"159.203.20.180"}]
["validated"]   "2021-04-19T14:59:34Z")
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

Does anyone have the same issue?

**Comment by KamilKeski** [comment]
Your endpoint is returning a 400.  Impossible to troubleshoot that without knowledge of the setup.  I would dig into why you are returning a 400

["error","detail"] "Fetching http://lab.smartipcloud.com/.well-known/acme-challenge/fldIKdGzgAEWBsKn0UVC4Q_fwk3zrq8o8QUg2cTrfqU: Timeout during connect (likely firewall problem)"
["error","status"] 400

**Comment by jobe1986** [comment]
I get a timeout attempting to connect to the httpd on lab.smartipcloud.com so can only conclude that either connections to ports 80 and 443 are blocked by your firewall, or there is no httpd running.

**Comment by kshah37** [comment]
I tried to put test file "Index.txt" in the same directory (/var/www/dehydrated) and it worked.  I was able to get the file.
https://lab.smartipcloud.com/.well-known/acme-challenge/index.txt
I also double checked my firewall .

**Comment by KamilKeski** [comment]
No one from the outside can reach lab.smartipcloud.com.  Unless you are whitelisting only letsencrypt source ip's it looks like you are blocking all traffic atm.

**Comment by kshah37** [comment]
I made these two changes and it worked. Thank you all for your support
1. There was extra space on my domain.txt file.
2. I opened 443 port .
