### ISSUE TITLE
Does dehydrated support listing of ISSUED certificates?

### ISSUE THREAD

**Issue by sheik1405** [dehydrated-io/dehydrated#821]
Hi ,
  Would like to know if dehydrated supports listing of the certificates that it has issued? Additionally informations like acme server details, next renewal time., ..etc. 

Sheik

**Comment by txr13** [comment]
I'm wondering what the use case for this is. If I want to know what certificates are currently configured, I'd look at domains.txt. If I want to know what certificates have been historically issued, I'd examine the contents of the certs (and archive, if applicable) directory. If I have, for some reason, forgotten what CA I'm using, I could examine any of my deployed certificates or check the config file. The next renewal time entirely depends on what I've configured in cron, the config file, and the expiry date for each certificate (which is printed during each cron run).

**Comment by lukas2511** [comment]
Currently the best way would be to simply look at your config for CA info and the domains.txt for a list of certificates, but everything else is kinda handled under the hood. I'm hoping to bring out a major rework for some parts of dehydrated later this year, that would easily allow for those information to be extracted, but for now you'd have to look at the actual certs for more details.
