### ISSUE TITLE
Request : Dehydrated support for using ECDSA in account creation

### ISSUE THREAD

**Issue by sheik1405** [dehydrated-io/dehydrated#827]
Hi,
  Our system restricts usage of RSA when running in secured crypto mode (FIPS/ Common criteria).   
In latest release, the dehydrated by default uses RSA for account creation, is it possible to provide ECDSA support for account creation.

**Comment by it-can** [comment]
https://community.letsencrypt.org/t/ecdsa-availability-in-production-environment/150679

**Comment by lukas2511** [comment]
Experimental support has been implemented. Would be great if some people could test it. For now `ACCOUNT_KEY_ALGO` has to be set in the config before registering an account. Documentation / Example configuration will follow when it's proven stable.
