### ISSUE TITLE
Cron renew forgets certificates if one fails

### ISSUE THREAD

**Issue by Zocker1999NET** [dehydrated-io/dehydrated#828]
- tested on Arch Linux and dehydrated version 0.7.1 (git revision unknown)

If `domains.txt` defines the following certificates
```
example.com www.example.com
example.net
www.example.net
```
and for example the challenge for `www.example.com` fails (due to DNS changes or anything else),
then the certificates for `example.net` and `www.example.net` will not be renewed even if the challenges there would work.

This should be fixed so dehydrated tries to renew all certificates and complains about all where the challenge failed instead of just complaining about the first failed.

**Comment by lukas2511** [comment]
Not a bug. There is a documented `KEEP_GOING` flag in the config that allows dehydrated to continue after an issue occurred.
