### ISSUE TITLE
deploy and validate one-by-one

### ISSUE THREAD

**Issue by Yannik** [dehydrated-io/dehydrated#832]
Hi,

currently, all challenges are deployed, and then all validations are done.

When using the same [acme-dns](https://github.com/joohoi/acme-dns) CNAME for multiple subdomains, this breaks validation, because the first challenge token is overwritten by latter ones.

Therefore, I'd like to propose a change that for each domain, the challenge is deployed and then validated.

**Comment by lukas2511** [comment]
If acme-dns overrides arguments instead of appending new ones that is broken behavior in acme-dns and not really a dehydrated issue.

See https://github.com/dehydrated-io/dehydrated/blob/master/docs/troubleshooting.md#dns-invalid-challenge-since-dehydrated-060--why-are-dns-challenges-deployed-first-and-verified-later

**Comment by Yannik** [comment]
Thanks, that link was helpful. I will have a look at what exactly acme-dns is doing that leads to this.

**Comment by Yannik** [comment]
For reference, the amount of txt records is limited to 2 by acme-dns ([source](https://github.com/joohoi/acme-dns/blob/v0.8/db.go#L256).

As a letsencrypt certificate can contain 100 domain names at most, upping this limit to 100 would support all usecases.
It would unfortunately also return old records. 
Do you think this would be a reasonable change or is there a better alternative?

**Comment by lukas2511** [comment]
With basically all other DNS implementations the flow would be to deploy tokens (either one or many, doesn't really matter), let them validate, and remove them afterwards. If acme-dns simply replaces/rotates old entries then it just sounds broken to me.
