### ISSUE TITLE
'org.pl' fails with ovh hook.

### ISSUE THREAD

**Issue by mkpb** [dehydrated-io/dehydrated#833]
Hi,

Got a problem with 'org.pl' domain with OVH hook.

OVH api claims that such resource does not exist.

All my other domains work fine - but all other domains are .com .org .studio .pl ones.
Only one domain of mine is org.pl and that particular one is failing.

**Comment by lukas2511** [comment]
This must be an issue with the hook script, doesn't sound like an issue with dehydrated.
