### ISSUE TITLE
Support sequential validations instead parallel validations

### ISSUE THREAD

**Issue by marcomsousa** [dehydrated-io/dehydrated#836]
Support sequential validations instead parallel validations

Right now if I execute dehydrated with two domains:
`dehydrated --cron --hook ./hooks.sh --challenge dns-01 --domain a.example.com --domain b.duckdns.org`
dehydrated try to deploy the two challenge at the same time. Only after, will responding the challenge for both domains. (parallel)

Since my scenario are:
- a.example.com CNAME  b.duckdns.org 
- _acme-challenge.a.example.com CNAME _acme-challengeb.duckdns.org

I can only validate if I can force dehydrated to do sequential validations.
Deploy 1 challenge, validate 1 challenge, clean, deploy 2 challenge, validate 2 challenge, clean. (sequential).

**Comment by lukas2511** [comment]
https://github.com/dehydrated-io/dehydrated/blob/master/docs/troubleshooting.md#dns-invalid-challenge-since-dehydrated-060--why-are-dns-challenges-deployed-first-and-verified-later
