### ISSUE TITLE
error when PREFERRED_CHAIN is specified but server does not provides altchains

### ISSUE THREAD

**Issue by zhangyoufu** [dehydrated-io/dehydrated#845]
The error message is confusing.
> ERROR: Problem connecting to server (post for ; curl returned with 3)

https://github.com/dehydrated-io/dehydrated/blob/91cccc0c234e4decf0a19595fa19a6f306788032/dehydrated#L1194-L1209

When `resheaders` does not contains  Link header w/ `rel="alternate"`, the loop body is still executed once with empty string assigned to `altcrturl`.

Can be reproduced by requesting ECDSA certificate from `--ca letsencrypt-test` at time of writing.

**Comment by lukas2511** [comment]
Should be fixed now. Thanks for reporting.
