### ISSUE TITLE
SANs broken since 31st

### ISSUE THREAD

**Issue by paulkaweb** [dehydrated-io/dehydrated#849]
Hello, we seem to be having issues creating/renewing certs since your last commits.. the problem seems to stem from this change:

```
-    altnames="$( <<<"${altnames}" _sed -e 's/^[[:space:]]*//; s/, /'"'$'\n'"'/g' )"
+    altnames="$( <<<"${altnames}" _sed -e 's/^[[:space:]]*//; s/, /\'$'\n''/g' )"
```

**now causes the following:**

root@foo:~# openssl req -noout -text -in /etc/apache2/ssl/www.example.com.csr | awk '/X509v3 Subject Alternative Name:/{print;getline;print;}' | tail -n1 | sed -r -e 's/^[[:space:]]*//; s/, /'"'$'\n'"'/g'
DNS:example.com'$'
'DNS:www.example.com

**what should happen:**

root@foo:~# openssl req -noout -text -in /etc/apache2/ssl/www.example.com.csr | awk '/X509v3 Subject Alternative Name:/{print;getline;print;}' | tail -n1 | sed -r -e 's/^[[:space:]]*//; s/, /\'$'\n''/g'
DNS:example.com
DNS:www.example.com

**Comment by lukas2511** [comment]
Thanks for reporting. I reverted that change and it should hopefully be working again.
