### ISSUE TITLE
Unable to sign a CSR that contains multiple alt_names 

### ISSUE THREAD

**Issue by Maanya-S** [dehydrated-io/dehydrated#851]
I have generated a CSR using the following config file - [csr.conf.txt](https://github.com/dehydrated-io/dehydrated/files/7533932/csr.conf.txt)
 (has 2 alt names).

This is the CSR that was generated - [example.csr.txt](https://github.com/dehydrated-io/dehydrated/files/7533940/example.csr.txt)

When I try to sign this csr, I am getting this error:

     user:/dehydrated # ./dehydrated/dehydrated --signcsr ./trial.csr
     INFO: Using main config file /dehydrated/config
     + Requesting new certificate order from CA...
     + Received 1 authorizations URLs from the CA
     + ERROR: An error occurred while sending post-request to
         https://localhost:8282/acme/abcdef_support@abc.com/authz/MAqR1vA3sT5f3V5ww1k4iqvmU1VlL5a0, (Status 400)       
         Details:
         HTTP/2 400
         cache-control: no-store
         content-type: application/problem+json
         link: <https://localhost:8282/acme/abcde_support@abc.com/directory>;rel="index"
         replay-nonce: bE56VTZEbjFTT2kyZ01vUGJTenoxVEZkZWpoaEhuQno
         content-length: 199
         date: Fri, 05 Nov 2021 05:54:12 GMT
         {"type":"urn:ietf:params:acme:error:malformed","detail":"authz MAqR1vA3sT5f3V5ww1k4iqvmU1VlL5a0, not found: key \u000b\u0000acme_authzs!\u0000MAqR1vA3sT5f3V5ww1k4iqvmU1VlL5a0, not found: not found"}

However when I try the same thing with just one alt name at a time in the config file like this - [csr2.conf.txt](https://github.com/dehydrated-io/dehydrated/files/7533946/csr2.conf.txt) , it works fine. 
Is this feature of adding multiple alt_names supported? And if it is, please let me know how I can make it work.

**Comment by lukas2511** [comment]
Can you check if this works with the latest release version of dehydrated? I think I might have broken a few things when I tried to clean up the code for shellcheck... I really need to get working on the automated testing system for stuff like this...
