### ISSUE TITLE
We are migrating our servers and I was wondering how to maintain the same let's encrypt account (id, keys).

### ISSUE THREAD

**Issue by arturmkrtchyan** [dehydrated-io/dehydrated#857]
Hey folks,

We are using lua-resty-auto-ssl which in turn uses dehydrated to dynamically generate certificates for our clients. We are using dedicated account to generate thousands of certificates. I assume it's important to maintain the same account. Would appreciate any guidance on how to properly copy over the account info to the new server.

Thanks!

**Comment by lukas2511** [comment]
I don't know what lua-resty-auto-ssl does, but normally dehydrated stores its accounts in the `accounts` subdirectory next to its config (or whatever is defined in the config itself). You should be able to just copy that directory over, and maybe also the `certs` directory to avoid reissuing thousands of certificates.
