### ISSUE TITLE
List of Variables That are Passed to hook.sh?

### ISSUE THREAD

**Issue by jeffsani** [dehydrated-io/dehydrated#864]
I seem to be missing the docs location of the list of variables that are passed to the hook script for challenge, clean, and cert operations.  Can someone point me in the right direction?

Thanks,
Jeff

**Comment by jobe1986** [comment]
All the individual parameters passed to each hook script call are listed in https://github.com/dehydrated-io/dehydrated/blob/master/docs/examples/hook.sh

As for environment variables available, I don't know of a specific doc without reading the source code.

**Comment by jeffsani** [comment]
This was exactly what I was looking for - thanks!
