### ISSUE TITLE
Question - DNS Challenge: Provider has no DNS API

### ISSUE THREAD

**Issue by tommyjlong** [dehydrated-io/dehydrated#876]
If I were to use the dns-01 method for a challenge, and my provider only supports manual entry of TXT records (which I understand can be supported by dehydrated), then for renewals, would I have to repeat this manual entry on each renewal?
Thanks.

**Comment by jobe1986** [comment]
Unfortunately the answer to that is yes. Additionally this is not something dehydrated has any control over either.

Simply put, Let's Encrypt only keeps domain validations valid for 30 days, after that they have to be revalidated.

**Comment by tommyjlong** [comment]
That's what I thought.  
Thanks for getting back on this.
