### ISSUE TITLE
Compare with ACME.sh

### ISSUE THREAD

**Issue by stokito** [dehydrated-io/dehydrated#879]
Sorry for a stupid question but it's really interesting to me. How the dehydrated is differs from the acme.sh?
As far I understood the ACME.sh is more bloated and it can work with wget instead of curl.
I have an OpenWrt router with small disk and thinking if it worth to switch to dehydrated.
Thank you

**Comment by lukas2511** [comment]
It's a completely different implementation, just happens to be written in the same (or at least compatible) scripting language. Personally never used acme.sh, so I can't give you any specific benefits or drawbacks between the two.

I personally used dehydrated on openwrt for a while, iirc it only really required installing some dependencies (bash, curl, openssl-bin, maybe sed/awk i'm not sure right now what is delivered in the default wrt install) and of course setting up some kind of webserver or dns hook script for domain authorization, then it should just work.
