### ISSUE TITLE
Future of dehydrated (dead?)

### ISSUE THREAD

**Issue by edrozenberg** [dehydrated-io/dehydrated#883]
My OS (Slackware) uses dehydrated as the default cert tool. Since this tool receives no changes since almost 1 yr ago, and almost no issue comments by the developer since 2020 (there was 1 in 2021), is the project dead?

Asking before putting in the work to set up this tool on a bunch of servers, vs. putting in the work to use acme.sh or some other similar Shell/C/Python tool which is still actively developed. I'm not tracking LetsEnc feature changes closely, but I can imagine that project making changes that might not be supported by a dessicated dehydrated project. Thanks.

**Comment by lukas2511** [comment]
Dehydrated is certainly not dead. I fix issues as they come along and am working behind the scenes on a major rewrite (which unfortunately is coming along rather slowly). I'm trying to stay up to day with changes to the protocol, which luckily became rather stable so dehydrated also keeps on working without any issues.

**Comment by edrozenberg** [comment]
That's good to hear, and it's fine as long as the current version continues to work. If a rewrite comes sometime in the future, great - I don't know the historical stats but many rewrites get abandoned before they can deliver. Thanks for this project.
