### ISSUE TITLE
Alias via domains.txt broken?

### ISSUE THREAD

**Issue by Lem** [dehydrated-io/dehydrated#887]
I tried to get a wildcard-only certificate for `*.example.com` via `domains.txt`. But it was not recognized by the script.

According to the documentation you can add the line `*.example.com > star_example_com`, but using the command `./dehydrated -d '*.example.com' -c` results in an error.

Using the command line argument (`./dehydrated -d '*.example.com' -c --alias star_example_com`) works fine.

Adding some debug lines I found out that the function `parse_domains_txt` seems to produce an output containing the '>', but it is missing in the variable `line` of the the for-loop responsible for the alias-logic (https://github.com/dehydrated-io/dehydrated/blob/master/dehydrated#L1656). 

Output of both commands:
```bash
 [bla@host dehydrated]$ ./dehydrated -d '*.example.com' -c 
# INFO: Using main config file /tmp/dehydrated/config
Processing *.example.com
ERROR: Please define a valid alias for your *.example.com wildcard-certificate. See domains.txt-documentation for more details.

[bla@host dehydrated]$ ./dehydrated -d '*.example.com' -c  --alias star_example_com
# INFO: Using main config file /tmp/dehydrated/config
Processing *.example.com
 + Creating new directory /tmp/dehydrated/certs/star_example_com ...
 + Signing domains...
[...]
```

**Comment by lukas2511** [comment]
That is intended behaviour. When you define domains via the cli arguments the `domains.txt` file gets ignored completely.
