### ISSUE TITLE
egrep: warning: egrep is obsolescent; using grep -E

### ISSUE THREAD

**Issue by christophfink** [dehydrated-io/dehydrated#889]
Thanks for this great tool, have been using it for a while, now.

Recently, I’ve started seeing warnings that `egrep` should be replaced with `grep -E`. I’m using **grep-3.8**.

For now, this is of course nothing more than a nuissance, but I would think that eventually, distributions will stop shipping an `egrep`.

**Comment by lukas2511** [comment]
fix was already in testing branch, merged together with a few other changes to master now, this issue should be fixed
