### ISSUE TITLE
Hijacked links on Wiki

### ISSUE THREAD

**Issue by AgentOak** [dehydrated-io/dehydrated#895]
Since the wiki is world-editable, someone replaced some links with an ip/location tracker

https://github.com/dehydrated-io/dehydrated/wiki/Home/_compare/eef948dac6598ee7c7b66dd0f180a14d667099d9...7252b4af3d58202876b67c994a3a86ca0a11a2a9

**Comment by lukas2511** [comment]
Thanks. I've removed the affected links (and some more.. :-/) and restricted write access to the wiki for now. I'll need to find a better solution for this...
