### ISSUE TITLE
hook.sh: line 217: $1: unbound variable

### ISSUE THREAD

**Issue by kjpetrie** [dehydrated-io/dehydrated#903]
Attempting to renew with LetsEncrypt in FreeBSD 13.1-RELEASE-p7 produces the error:
/usr/local/etc/dehydrated/hook.sh: line 217: $1: unbound variable

Line 217 appears to be the following function:

```
startup_hook() {
  # This hook is called before the cron command to do some initial tasks
  # (e.g. starting a webserver).

  :
}

```

**Comment by lukas2511** [comment]
Can you give any more details? From what I see the hook scripts aren't even configured by default in the freebsd dehydrated port. And the hook script should never be called without an argument so `$1` should always be defined.

**Comment by kjpetrie** [comment]
Thank you! It seems a new FreeBSD package built by my poudriere on 17th January inserted a hook.sh script which was called automatically since I had /usr/local/etc/dehydrated configured as CONFGI_D. Maybe that was wrong. I shall try commenting it out.
