### ISSUE TITLE
/bin/config: line 6: use: command not found

### ISSUE THREAD

**Issue by PatricDahl** [dehydrated-io/dehydrated#904]
Hi,

I'm receiving an error message when executing dehydrated command.

./dehydrated -f config -c --force --force-validation
 INFO: Using main config file config
/bin/config: line 6: use: command not found

./dehydrated -v
 INFO: Using main config file /shared/dehydrated/config
Dehydrated by Lukas Schauer
https://dehydrated.io

Dehydrated version: 0.7.2
GIT-Revision: unknown

OS: CentOS Linux 7 (Core)
Used software:
 bash: 4.2.46(2)-release
 curl: 7.47.1
 awk: GNU Awk 4.0.2
 sed: sed (GNU sed) 4.2.2
 mktemp: mktemp (GNU coreutils) 8.22
 grep: grep (GNU grep) 2.20
 diff: diff (GNU diffutils) 3.3
 openssl: OpenSSL 1.0.2s-fips  28 May 2019

**Comment by lukas2511** [comment]
Looks like you are currently in your `/bin` directory and specifying `config` as config file, which probably also is a binary in that directory. No idea what you were expecting to happen here.
