### ISSUE TITLE
Do I need to define all hook functions?

### ISSUE THREAD

**Issue by adrian5** [dehydrated-io/dehydrated#927]
I noticed that having only a subset of functions makes **dehydrated** error out. Do I take the [hook.sh](https://github.com/dehydrated-io/dehydrated/blob/master/docs/examples/hook.sh) example file as-is and only modify the function bodies I'm interested in, or what's the recommended approach?

I think I may only need `deploy_cert()` and `deploy_ocsp()` to do any actual work.

**Comment by adrian5** [comment]
It just dawned on me that the handler function at the bottom isn't binding. Do assume correctly that I can just do:
```bash
HANDLER="$1"; shift
if [[ "${HANDLER}" =~ ^(deploy_cert|deploy_ocsp)$ ]]; then # Ignore all handler requests except 2
  "$HANDLER" "$@"
fi
```
?

**Comment by lukas2511** [comment]
You only need to handle hook functions you really need. You can rewrite the hook script completely however you like it, it could also be written in another scripting language or even a compiled binary, the only thing that matters is that it can be run from the command line and accepts the hook function name as first parameter.
