### ISSUE TITLE
Letsencrypt changes broke dehydrated

### ISSUE THREAD

**Issue by orev75** [dehydrated-io/dehydrated#948]
Dehydrated no longer works. The execution failed with the following problem.
```
ERROR: Problem connecting to server (get for https://acme-v02.api.letsencrypt.org/directory; curl returned with 23)
EXPECTED value GOT EOF
```
According to Kerio, changes were made by Let's Encrypt : https://support.kerioconnect.gfi.com/hc/en-us/articles/19547534733202-Troubleshooting-Let-s-Encrypt-Failure-contacting-https-acme-v02-api-letsencrypt-org-directory-rel-index-to-read-header

**Comment by jobe1986** [comment]
Have you tried using the latest version from the github repo? As I am not experiencing this issue with the latest version myself. And to confirm that I have had a certificate renew today where as the Keno article was posted 24 days ago.

**Comment by orev75** [comment]
Yes, I did try the latest version of the master branch (last modified in December 2023).

**Comment by orev75** [comment]
I tried again today and everything works now, maybe a network problem with my ISP.
Thanks for your reply.
